# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-18 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xiangmu',
            options={'verbose_name': '运动项目', 'verbose_name_plural': '运动项目'},
        ),
    ]
