# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chengji', '0004_auto_20180604_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chengjidate',
            name='jibie',
            field=models.CharField(choices=[('guoji', '国际'), ('quanguo', '全国'), ('shengji', '省级')], default='全国', max_length=6, verbose_name='赛事级别'),
        ),
    ]
