# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('yundongyuan', '0005_auto_20180527_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChengjiSh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='生化日期')),
                ('gaotong', models.FloatField(verbose_name='睾酮')),
                ('nandufen', models.FloatField(verbose_name='难度分')),
                ('wanchengfen', models.FloatField(verbose_name='完成分')),
                ('zongfen', models.FloatField(verbose_name='总分')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChengjiSh_xingming', to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name_plural': '成绩-生化',
                'verbose_name': '成绩-生化',
            },
        ),
        migrations.CreateModel(
            name='XunlianCj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='训练日期')),
                ('mingcheng', models.CharField(blank=True, max_length=50, null=True, verbose_name='赛事名称')),
                ('tianshu', models.IntegerField(verbose_name='累计训练天数')),
                ('nandufen', models.FloatField(verbose_name='难度分')),
                ('wanchengfen', models.FloatField(verbose_name='完成')),
                ('zongfen', models.FloatField(verbose_name='总分')),
                ('sbcishu', models.IntegerField(verbose_name='失败次数')),
                ('sbyuanyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='失败原因')),
                ('xiangmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='XunlianCj_xiangmu', to='events.Xiangmu', verbose_name='体操项目')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='XunlianCj_xingming', to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name_plural': '训练-成绩',
                'verbose_name': '训练-成绩',
            },
        ),
        migrations.CreateModel(
            name='XunlianSh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='训练日期')),
                ('gaotong', models.FloatField(verbose_name='睾酮')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='XunlianSh_xingming', to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name_plural': '训练-生化',
                'verbose_name': '训练-生化',
            },
        ),
    ]
