# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20181203_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='xunliansh',
            name='leijishijian',
            field=models.IntegerField(default=0, verbose_name='累计训练天数'),
        ),
    ]
