# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_xunliansh_leijishijian'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengjish',
            name='jisuanjimei',
            field=models.FloatField(default=0, verbose_name='肌酸激酶'),
        ),
        migrations.AddField(
            model_name='chengjish',
            name='niaosudan',
            field=models.FloatField(default=0, verbose_name='尿素氮'),
        ),
        migrations.AddField(
            model_name='chengjish',
            name='pizhichun',
            field=models.FloatField(default=0, verbose_name='皮质醇'),
        ),
    ]
