# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yundongyuan', '0005_auto_20180527_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
