# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180425_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
    ]
