# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yundongyuan', '0006_auto_20180604_2100'),
        ('events', '0002_auto_20180618_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingtu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='饼图标题')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='饼图')),
            ],
            options={
                'verbose_name': '训练次数饼图',
                'verbose_name_plural': '训练次数饼图',
            },
        ),
        migrations.CreateModel(
            name='XunlianDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='训练日期')),
                ('content', models.CharField(blank=True, max_length=50, null=True, verbose_name='训练内容')),
                ('xiangmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Xiangmu', verbose_name='体操项目')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name': '训练记录',
                'verbose_name_plural': '训练记录',
            },
        ),
        migrations.CreateModel(
            name='XunlianSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='训练月份')),
                ('sum', models.IntegerField(verbose_name='训练总次数')),
                ('xiangmu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Xiangmu', verbose_name='体操项目')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name': '训练总数统计',
                'verbose_name_plural': '训练总数统计',
            },
        ),
    ]
