# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingtu1',
            name='introduce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='图表简介'),
        ),
    ]
