# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunlian', '0005_auto_20180527_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xunliandate',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='训练内容'),
        ),
    ]
